var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", "namespacedocstring" ],
    [ "ns", "namespacens.html", "namespacens" ],
    [ "pyexample", "namespacepyexample.html", "namespacepyexample" ],
    [ "A", "class_a.html", "class_a" ],
    [ "Afterdoc_Test", "class_afterdoc___test.html", "class_afterdoc___test" ],
    [ "Autolink_Test", "class_autolink___test.html", "class_autolink___test" ],
    [ "B", "class_b.html", "class_b" ],
    [ "C", "class_c.html", "class_c" ],
    [ "C1", "class_c1.html", null ],
    [ "C2", "class_c2.html", null ],
    [ "C3", "class_c3.html", null ],
    [ "C4", "class_c4.html", null ],
    [ "C5", "class_c5.html", null ],
    [ "Car", "struct_car.html", "struct_car" ],
    [ "CoordStruct", "struct_coord_struct.html", "struct_coord_struct" ],
    [ "D", "class_d.html", "class_d" ],
    [ "E", "class_e.html", null ],
    [ "Enum_Test", "class_enum___test.html", "class_enum___test" ],
    [ "Example_Test", "class_example___test.html", "class_example___test" ],
    [ "Fn_Test", "class_fn___test.html", "class_fn___test" ],
    [ "Include_Test", "class_include___test.html", "class_include___test" ],
    [ "Javadoc_Test", "class_javadoc___test.html", "class_javadoc___test" ],
    [ "Memgrp_Test", "class_memgrp___test.html", "class_memgrp___test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "struct_object.html", "struct_object" ],
    [ "Overload_Test", "class_overload___test.html", "class_overload___test" ],
    [ "Par_Test", "class_par___test.html", null ],
    [ "QTstyle_Test", "class_q_tstyle___test.html", "class_q_tstyle___test" ],
    [ "SomeNiceClass", "class_some_nice_class.html", null ],
    [ "String", "class_string.html", "class_string" ],
    [ "Tag", "class_tag.html", "class_tag" ],
    [ "Test", "class_test.html", "class_test" ],
    [ "Test< T * >", "class_test_3_01_t_01_5_01_4.html", "class_test_3_01_t_01_5_01_4" ],
    [ "Test< void *, 200 >", "class_test_3_01void_01_5_00_01200_01_4.html", "class_test_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "struct_truck.html", "struct_truck" ],
    [ "Vehicle", "struct_vehicle.html", "struct_vehicle" ]
];